### ISSUE TITLE
Cannot install module from URL

### ISSUE THREAD

**Issue by gormley-logan** [orangetruth/dnd5e-status-icons#1]
When trying to install the module by giving the link to the raw module.json on github, I encounter this error:
`[dnd5e-status-icons] Metadata validation failed for module "dnd5e-status-icons": The file "lang/en.json" included by module dnd5e-status-icons does not exist`
I am running Foundry Version 10 Build 291 which from my understanding is the verified build for the module.

**Comment by mahuntington** [comment]
@gormley-logan did you ever figure this out?

**Comment by mahuntington** [comment]
@gormley-logan I have a pull-request in for the fix: https://github.com/orangetruth/dnd5e-status-icons/pull/2.  Not entirely sure this is the perfect thing to do, but it worked for me at least

**Comment by orangetruth** [comment]
@gormley-logan @mahuntington apologies, my d&d group isn't using Foundry anymore (we play in person now), so I'm not actively maintaining this. I did merge that pull request, I hope that helps

**Comment by gormley-logan** [comment]
Yes, sorry, I finally got around to trying the module again. For anyone else trying to install the module, make sure to grab the URL listed next to "manifest" in the modules.json file.
